# Generated by Django 5.1.5 on 2025-02-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0002_patientdb_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdb',
            name='Emergency',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
