# Generated by Django 5.1.5 on 2025-02-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0005_pharmacistdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceptionistDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Last_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('Gender', models.CharField(blank=True, max_length=100, null=True)),
                ('Phone_Number', models.IntegerField(blank=True, null=True)),
                ('Address', models.CharField(blank=True, max_length=255, null=True)),
                ('Email_Id', models.EmailField(blank=True, max_length=100, null=True)),
                ('Username', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('Password', models.CharField(blank=True, max_length=255, null=True)),
                ('Status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=50)),
                ('Joining_Date', models.DateField(blank=True, null=True)),
                ('Experience', models.IntegerField(blank=True, null=True)),
                ('Qualification', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
