# Generated by Django 5.1.5 on 2025-02-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0006_receptionistdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineCategoryDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=255, unique=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Updated_at', models.DateTimeField(auto_now=True)),
                ('Status', models.BooleanField(default=True)),
            ],
        ),
    ]
