# Generated by Django 5.1.5 on 2025-02-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0007_medicinecategorydb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinecategorydb',
            name='Category_name',
        ),
        migrations.AlterField(
            model_name='medicinecategorydb',
            name='Status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=50),
        ),
        migrations.AddField(
            model_name='medicinecategorydb',
            name='Category_Name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
