# Generated by Django 5.1.5 on 2025-02-10 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0009_medicinedb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicinedb',
            old_name='name',
            new_name='Name',
        ),
    ]
