# Generated by Django 5.1.5 on 2025-02-14 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0010_rename_name_medicinedb_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicinecategorydb',
            old_name='Created_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='medicinecategorydb',
            old_name='Updated_at',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='medicinecategorydb',
            name='Category_Name',
        ),
        migrations.RemoveField(
            model_name='medicinecategorydb',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='medicinecategorydb',
            name='Status',
        ),
        migrations.CreateModel(
            name='PrescriptionDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=100)),
                ('instructions', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_prescriptions', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('doctor', 'Doctor'), ('pharmacist', 'Pharmacist'), ('admin', 'Admin')], default='admin', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='medicinecategorydb',
            name='category_name',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='medicinecategorydb',
            name='description',
            field=models.CharField(default='No description', max_length=500),
        ),
        migrations.AddField(
            model_name='medicinecategorydb',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
    ]
