# Generated by Django 5.1.5 on 2025-02-18 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0011_rename_created_at_medicinecategorydb_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinedb',
            name='category',
        ),
        migrations.RemoveField(
            model_name='medicinedb',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='medicinedb',
            name='manufacturer',
        ),
        migrations.AddField(
            model_name='medicinedb',
            name='symptoms',
            field=models.TextField(default='No symptoms provided', help_text='Enter symptoms separated by commas'),
        ),
        migrations.AlterField(
            model_name='medicinedb',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='MedicineCategoryDb',
        ),
    ]
