# Generated by Django 5.1.5 on 2025-02-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0012_remove_medicinedb_category_and_more'),
        ('userapp', '0007_symptom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinedb',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='medicinedb',
            name='symptoms',
        ),
        migrations.AddField(
            model_name='medicinedb',
            name='symptoms',
            field=models.ManyToManyField(related_name='medicines', to='userapp.symptom'),
        ),
    ]
