# Generated by Django 5.1.5 on 2025-02-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0013_alter_medicinedb_price_remove_medicinedb_symptoms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinedb',
            name='symptoms',
        ),
        migrations.AddField(
            model_name='medicinedb',
            name='symptoms',
            field=models.TextField(default='No symptoms provided', help_text='Enter symptoms separated by commas'),
        ),
    ]
