# Generated by Django 5.1.5 on 2025-02-18 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_registerdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='symptoms_treated',
            field=models.TextField(default='No Symptoms'),
            preserve_default=False,
        ),
    ]
