# Generated by Django 5.1.5 on 2025-03-25 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptomform',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='symptomform',
            name='patient',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
        migrations.DeleteModel(
            name='SymptomForm',
        ),
    ]
