# Generated by Django 5.1.5 on 2025-03-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorApp', '0003_patientform_prescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientform',
            old_name='submitted_at',
            new_name='date_submitted',
        ),
        migrations.RenameField(
            model_name='prescription',
            old_name='prescribed_at',
            new_name='date_prescribed',
        ),
        migrations.RemoveField(
            model_name='patientform',
            name='is_reviewed',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='prescription_text',
        ),
        migrations.AddField(
            model_name='patientform',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Reviewed', 'Reviewed')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='prescription',
            name='dosage',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicine',
            field=models.CharField(default='exit', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient_name',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
    ]
