# Generated by Django 5.1.5 on 2025-03-25 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorApp', '0006_symptomform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='medicine',
            new_name='medicines',
        ),
    ]
