# Generated by Django 5.1.5 on 2025-03-25 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorApp', '0007_rename_medicine_prescription_medicines'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='medicines',
            new_name='medicine',
        ),
    ]
